#==============================
# General site config
#==============================

name: "Luke Skinner"
url: http://lukeskinner.me

markdown: kramdown


#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]


#==============================
# Plugins
#==============================
