source 'http://rubygems.org'

gem "jekyll-assets"

gem "coffee-script" 
gem "uglifier"
gem "sass"

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']